# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulerequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerequest',
            name='contact_number',
            field=models.CharField(default=81989238, max_length=120),
            preserve_default=False,
        ),
    ]
