# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('faculty', models.CharField(max_length=120)),
                ('tuition_cost', models.IntegerField(default=10)),
                ('points', models.IntegerField(default=100)),
                ('module_to_offer_1', models.CharField(blank=True, max_length=120)),
                ('module_to_offer_2', models.CharField(blank=True, max_length=120)),
                ('module_to_offer_3', models.CharField(blank=True, max_length=120)),
                ('place_of_convenience', models.CharField(max_length=120)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
